name: Python Unit Tests

on:
  push:	
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3
  - name: Setup Python environment
    uses: actions/setup-python@v4
    with:
      python-version: '3.x'
  - name: Install Hatch
    uses: pypa/hatch@install
  - name: Install MuSE
    run: |
      python -m pip install --upgrade pip
      python -m hatch build -t wheel
      python -m pip install dist/*.whl --break-system-packages
  - name: Run tests
    run: |
      python -m hatch test