name: Python Unit Tests

on:
  push:	
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3
  - name: Setup Python environment
    uses: actions/setup-python@v4
    with:
      python-version: '3.x'

  - name: Install dependencies
    run: |
      export MUSE_HOME=$GITHUB_WORKSPACE
      ./install.sh
  - name: Run tests
    run: |
     echo $MUSE_HOME
     pwd
     ls
     python -m unittest discover muse/tests -p '*py'