name: Python Unit Tests

on:
  push:	
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3
  - name: Setup Python environment
    uses: actions/setup-python@v4
    with:
      python-version: '3.x'
  - name: Install python3-venv
    run: sudo apt-get update && sudo apt-get install -y python3-venv
  - name: Install dependencies
    run: |
      export MUSE_HOME=$GITHUB_WORKSPACE
      python -m pip install --upgrade pip
      ./install.bash
      python -m pip install -r requirements.txt
  - name: Run tests
    run: |
     export MUSE_HOME=$GITHUB_WORKSPACE
     echo $MUSE_HOME
     pwd
     ls
     python -m unittest discover tests -p '*py'